version: "3.8"

services:
 
  backend:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - app_data:/app/logs
    networks:
     - app-net


volumes:
  app_data:   
networks:
  app-net:
    driver: bridge
